build:
  maxIssues: 0

style:
  MagicNumber:
    active: false
  ReturnCount:
    active: false
  WildcardImport:
    active: false

complexity:
  LongMethod:
    active: false
  TooManyFunctions:
    active: false
  LongParameterList:
    active: true
    functionThreshold: 8
    constructorThreshold: 8
    ignoreDefaultParameters: true
    ignoreDataClasses: true
    ignoreAnnotated:
      - "Composable"

naming:
  FunctionNaming:
    active: true
    ignoreAnnotated:
      - "Composable"
  TopLevelPropertyNaming:
    active: false

empty-blocks:
  EmptyFunctionBlock:
    active: false
